title: 'The food game '
description: Food will drop so try and get it.
template:
  repo: the-food-game-template
  name: the-food-game
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
